name: Build macOS Executable

on:
  push:
    branches:
      - main
    tags:
      - 'v*'  # Run this workflow when a new tag is pushed

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pillow
        pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller --windowed --onefile --icon=icon.ico main.py

    - name: Create archive
      run: |
        tar -czvf macos-executable.tar.gz -C dist .

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: macos-executable
        path: macos-executable.tar.gz

    - name: Get latest release
      id: get_latest_release
      uses: octokit/request-action@v2.0.21
      with:
        route: GET /repos/${{ github.repository }}/releases/latest
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

    - name: Upload Release Asset
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        LATEST_RELEASE_ID=$(echo "${{ steps.get_latest_release.outputs.data }}" | jq -r '.id')
        UPLOAD_URL=$(echo "${{ steps.get_latest_release.outputs.data }}" | jq -r '.upload_url' | sed 's/{?name,label}//')
        curl -XPOST -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: application/gzip" \
            --data-binary @macos-executable.tar.gz \
            "$UPLOAD_URL?name=macos-executable.tar.gz"
