name: AutoRelease

on:
  push:
    branches:
      - main  # Run this workflow when there is a push to the main branch

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pillow
        pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller --windowed --onefile --icon=icon.ico main.py

    - name: Create archive
      run: |
        tar -czvf macos-executable.tar.gz -C dist .

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: macos-executable
        path: macos-executable.tar.gz

    - name: Create or Update GitHub Release
      id: create_release
      uses: CupOfTea696/gh-action-auto-release@v1.0.0
      with:
        title: "Release: $version"
        tag: "v$semver"
        draft: false
        changelog: CHANGELOG.md
        changelog-entry: $version
        regex: "/^Release: #{semver}$/i"
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

    - name: Upload Release Asset
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        UPLOAD_URL=$(echo "${{ steps.create_release.outputs.upload_url }}" | sed 's/{?name,label}//')
        curl -XPOST -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: application/gzip" \
            --data-binary @macos-executable.tar.gz \
            "$UPLOAD_URL?name=macos-executable.tar.gz"
